version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: digitalhypertech/reverseproxy:v1
  backend_user:
    build:
      context: ./udagram-api-users
    image: digitalhypertech/udagram-api-users:v2
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: digitalhypertech/udagram-api-feed:v2
  frontend:
    build:
      context: ./udagram-frontend
    image: digitalhypertech/udagram-frontend:v4